# Generated by Django 3.1.7 on 2021-03-09 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('color', models.CharField(default='primary', max_length=8)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.card')),
                ('name', models.CharField(max_length=256)),
            ],
            bases=('board.card',),
        ),
        migrations.CreateModel(
            name='ProgressCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.card')),
                ('name', models.CharField(max_length=2500)),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('has_limit', models.BooleanField(default=True)),
            ],
            bases=('board.card',),
        ),
        migrations.CreateModel(
            name='TasksCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.card')),
                ('name', models.CharField(max_length=2500)),
            ],
            bases=('board.card',),
        ),
        migrations.CreateModel(
            name='TextCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.card')),
                ('name', models.CharField(max_length=2500)),
            ],
            bases=('board.card',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('completed', models.BooleanField(default=False)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.taskscard')),
            ],
        ),
        migrations.CreateModel(
            name='HabitCardDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_week', models.DateField()),
                ('days', models.CharField(max_length=7)),
                ('habit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.habitcard')),
            ],
            options={
                'unique_together': {('habit_card', 'start_week')},
            },
        ),
    ]
