# Generated by Django 3.1.7 on 2021-03-17 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210314_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 20, 0, 5, 188704)),
        ),
    ]
