# Generated by Django 3.1.7 on 2021-03-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20210323_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HabitCardDay',
            new_name='HabitDay',
        ),
    ]
